name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build APK with Cordova
      run: |
        npm install -g cordova
        cordova create pser-app com.pser.survey "PSER Survey"
        cd pser-app
        cp -r ../* www/
        cordova platform add android
        cordova build android
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: pser-survey-apk
        path: pser-app/platforms/android/app/build/outputs/apk/debug/*.apk
